import {
  Code2, Cloud, ShieldCheck, Cpu, BarChart3,
  Server, Smartphone, Palette, LayoutGrid, Lightbulb,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type ServiceData = {
  slug:      string;
  num:       string;
  icon:      LucideIcon;
  name:      string;
  tagline:   string;
  desc:      string;
  overview:  string;
  color:     string;
  glow:      string;
  tags:      string[];
  features:  { title: string; body: string }[];
  process:   { step: string; title: string; body: string }[];
  stack:     string[];
};

const SERVICES: ServiceData[] = [
  {
    slug:    "software-development",
    num:     "01",
    icon:    Code2,
    name:    "Software Development",
    tagline: "From zero to production. Fast.",
    desc:    "Custom web apps, APIs, and enterprise platforms engineered for scale. From zero-to-one MVPs to complex systems.",
    overview:"We design and build software that solves real problems — not just code that ships. Whether you need an MVP in four weeks or a multi-tenant enterprise platform, we architect it right from day one so it scales without pain.",
    color:   "#3B82F6",
    glow:    "rgba(59,130,246,0.18)",
    tags:    ["React", "Next.js", "Node.js", "Python", "TypeScript", "PostgreSQL"],
    features: [
      { title: "Full-Stack Engineering",    body: "Frontend, backend, and everything in between — one team, one codebase, zero handoff friction." },
      { title: "API Design & Integration",  body: "RESTful and GraphQL APIs built to last, plus seamless third-party integrations that just work." },
      { title: "MVP to Scale",              body: "We know when to move fast and when to slow down. We won't let tech debt kill your momentum." },
      { title: "Quality Assurance",         body: "Automated testing, CI/CD pipelines, and code reviews so bugs don't reach your users." },
      { title: "Performance Engineering",   body: "Sub-second load times, optimised queries, and infrastructure that handles traffic spikes." },
      { title: "Ongoing Maintenance",       body: "We don't disappear after launch. Retainers, SLAs, and dedicated support keep your product healthy." },
    ],
    process: [
      { step: "01", title: "Discovery",     body: "We deep-dive into your problem, users, and constraints before writing a single line of code." },
      { step: "02", title: "Architecture",  body: "System design, tech stack decisions, and a roadmap the whole team can execute against." },
      { step: "03", title: "Build & Test",  body: "Agile sprints with weekly demos, automated tests, and continuous deployment from day one." },
      { step: "04", title: "Launch & Own",  body: "Production-ready deployment, monitoring, and a handover — or we stay on retainer." },
    ],
    stack: ["React", "Next.js", "TypeScript", "Node.js", "Python", "FastAPI", "PostgreSQL", "Redis", "Docker", "GitHub Actions"],
  },
  {
    slug:    "cloud-computing",
    num:     "02",
    icon:    Cloud,
    name:    "Cloud Computing",
    tagline: "Modern infrastructure that scales with you.",
    desc:    "Cloud migration, infrastructure design, and managed services on AWS, Azure & GCP.",
    overview:"Moving to the cloud or optimising what you already have? We design and manage cloud infrastructure that is secure, cost-efficient, and built to grow — without the complexity of managing it yourself.",
    color:   "#06B6D4",
    glow:    "rgba(6,182,212,0.18)",
    tags:    ["AWS", "Azure", "GCP", "Terraform", "Kubernetes", "Docker"],
    features: [
      { title: "Cloud Migration",           body: "Lift-and-shift or full re-architecture — we migrate workloads with zero downtime and minimum disruption." },
      { title: "Infrastructure as Code",    body: "Terraform and Pulumi configs that make your infra reproducible, auditable, and version-controlled." },
      { title: "Kubernetes Orchestration",  body: "Container-native deployments with auto-scaling, rolling updates, and self-healing clusters." },
      { title: "Cost Optimisation",         body: "Reserved instances, right-sizing, and continuous FinOps reviews that cut your cloud bill." },
      { title: "Managed Services",          body: "24/7 monitoring, alerting, and incident response so your infrastructure never keeps you up at night." },
      { title: "Disaster Recovery",         body: "Multi-region failover, automated backups, and RPO/RTO targets that give you real peace of mind." },
    ],
    process: [
      { step: "01", title: "Assessment",    body: "Audit your current environment, map dependencies, and size the target architecture." },
      { step: "02", title: "Design",        body: "Cloud architecture blueprints, security baselines, and a migration plan with risk mitigations." },
      { step: "03", title: "Migrate",       body: "Phased migration with automated testing and rollback capability at every stage." },
      { step: "04", title: "Optimise",      body: "Post-migration performance tuning, cost reviews, and ongoing managed support." },
    ],
    stack: ["AWS", "Azure", "GCP", "Terraform", "Kubernetes", "Helm", "Docker", "Prometheus", "Grafana", "GitHub Actions"],
  },
  {
    slug:    "cybersecurity",
    num:     "03",
    icon:    ShieldCheck,
    name:    "Cybersecurity",
    tagline: "Security that doesn't slow you down.",
    desc:    "Penetration testing, threat monitoring, and enterprise security architecture. SOC2, ISO 27001 compliance.",
    overview:"Your security posture is only as strong as its weakest point. We find those points before attackers do — and then harden them. From compliance frameworks to real-time threat detection, we keep your business protected.",
    color:   "#EF4444",
    glow:    "rgba(239,68,68,0.18)",
    tags:    ["Pen Testing", "SIEM", "Zero Trust", "SOC2", "ISO 27001", "VAPT"],
    features: [
      { title: "Penetration Testing",       body: "Black-box, white-box, and grey-box pen tests with detailed remediation reports your team can act on." },
      { title: "Security Architecture",     body: "Zero-trust frameworks, network segmentation, and identity management that fit your threat model." },
      { title: "Compliance Consulting",     body: "SOC2, ISO 27001, NDPR, and PCI-DSS gap analysis and remediation roadmaps." },
      { title: "24/7 Threat Monitoring",    body: "SIEM-powered monitoring with real-time alerting and an incident response team on standby." },
      { title: "Vulnerability Management",  body: "Continuous scanning, prioritised remediation, and risk-based patching programmes." },
      { title: "Security Training",         body: "Phishing simulations and staff awareness training that turn your team into your first line of defence." },
    ],
    process: [
      { step: "01", title: "Scope & Recon", body: "Define scope, gather intelligence, and map attack surface before any testing begins." },
      { step: "02", title: "Assess",        body: "Active penetration testing, vulnerability scanning, and configuration reviews." },
      { step: "03", title: "Report",        body: "Prioritised findings with CVSS scores and step-by-step remediation guidance." },
      { step: "04", title: "Remediate & Re-test", body: "Support your team through remediation, then re-test to confirm vulnerabilities are closed." },
    ],
    stack: ["Burp Suite", "Metasploit", "Nessus", "Splunk", "CrowdStrike", "Wazuh", "OWASP ZAP", "Nmap", "Wireshark"],
  },
  {
    slug:    "emerging-tech",
    num:     "04",
    icon:    Cpu,
    name:    "AI & Emerging Tech",
    tagline: "Tomorrow's technology, today.",
    desc:    "AI/ML integration, LLM-powered products, and IoT solutions that make emerging technology practical.",
    overview:"Cutting-edge technology is only valuable when it solves real problems. We cut through the hype and implement AI, ML, and IoT solutions that deliver measurable business outcomes — not demos that never ship.",
    color:   "#8B5CF6",
    glow:    "rgba(139,92,246,0.18)",
    tags:    ["OpenAI", "LangChain", "IoT", "MLOps", "Blockchain", "Computer Vision"],
    features: [
      { title: "LLM-Powered Products",      body: "ChatGPT, Claude, and open-source LLM integrations that automate workflows and delight users." },
      { title: "ML Model Development",      body: "Custom models trained on your data — from classification to forecasting and anomaly detection." },
      { title: "AI Automation",             body: "Intelligent process automation that replaces repetitive tasks and scales with your business." },
      { title: "IoT Solutions",             body: "End-to-end IoT architecture from edge devices to cloud dashboards and real-time alerting." },
      { title: "Computer Vision",           body: "Object detection, OCR, and visual inspection systems for manufacturing, retail, and logistics." },
      { title: "MLOps & Deployment",        body: "Production ML pipelines with monitoring, versioning, and continuous retraining loops." },
    ],
    process: [
      { step: "01", title: "Use-Case Design", body: "Identify the highest-value AI use cases and define success metrics before any model work." },
      { step: "02", title: "Data & Model",    body: "Data pipeline build, model selection, training, and evaluation with your real data." },
      { step: "03", title: "Integrate",       body: "Seamless integration into your existing systems with APIs, SDKs, or embedded solutions." },
      { step: "04", title: "Monitor & Improve", body: "Continuous monitoring of model performance and iterative improvement post-launch." },
    ],
    stack: ["Python", "PyTorch", "OpenAI API", "LangChain", "Hugging Face", "FastAPI", "MLflow", "AWS SageMaker", "Pinecone"],
  },
  {
    slug:    "data-analytics",
    num:     "05",
    icon:    BarChart3,
    name:    "Data Analytics",
    tagline: "Turn data into decisions.",
    desc:    "Turn raw data into business intelligence. BI dashboards, ML pipelines, and modern data engineering at scale.",
    overview:"Most businesses are sitting on a goldmine of data they can't use. We build the pipelines, warehouses, and dashboards that turn raw data into clear, actionable intelligence — so decisions get made with facts, not instinct.",
    color:   "#F97316",
    glow:    "rgba(249,115,22,0.18)",
    tags:    ["Power BI", "Python", "SQL", "dbt", "Snowflake", "Machine Learning"],
    features: [
      { title: "Data Engineering",          body: "ETL/ELT pipelines that reliably move and transform data from any source into your warehouse." },
      { title: "BI Dashboards",             body: "Power BI, Looker, and custom dashboards that give every stakeholder exactly what they need." },
      { title: "Data Warehouse Design",     body: "Snowflake, BigQuery, and Redshift architectures optimised for your query patterns and scale." },
      { title: "Predictive Analytics",      body: "Forecasting models that help you anticipate demand, churn, and risk before they hit." },
      { title: "Real-Time Analytics",       body: "Streaming pipelines with Kafka and Flink that power live dashboards and instant insights." },
      { title: "Data Governance",           body: "Data cataloguing, lineage tracking, and quality monitoring that keeps your data trustworthy." },
    ],
    process: [
      { step: "01", title: "Audit",         body: "Map your current data sources, quality issues, and the decisions you need data to support." },
      { step: "02", title: "Architect",     body: "Design the data model, warehouse structure, and pipeline architecture." },
      { step: "03", title: "Build",         body: "Implement pipelines, transformations, and dashboards with automated testing at each layer." },
      { step: "04", title: "Empower",       body: "Train your team, document the platform, and hand over a data stack they can actually use." },
    ],
    stack: ["Python", "dbt", "Airflow", "Snowflake", "BigQuery", "Power BI", "Looker", "Kafka", "Spark", "PostgreSQL"],
  },
  {
    slug:    "it-support",
    num:     "06",
    icon:    Server,
    name:    "IT Support & Helpdesk",
    tagline: "Always on. Always there.",
    desc:    "24/7 managed IT support with guaranteed sub-1hr first-response SLA. Remote monitoring and on-site capability.",
    overview:"Technology failures cost money. Our managed IT support service keeps your systems running, your team productive, and your business protected — with a dedicated team available around the clock and a response time guaranteed by SLA.",
    color:   "#10B981",
    glow:    "rgba(16,185,129,0.18)",
    tags:    ["24/7 SLA", "Remote Support", "On-site", "Infrastructure", "Helpdesk"],
    features: [
      { title: "24/7 Helpdesk",             body: "Multi-channel support via phone, email, and chat with a human response in under 60 minutes." },
      { title: "Remote Monitoring",          body: "Proactive monitoring of servers, networks, and endpoints that catches issues before users notice." },
      { title: "On-site Support",            body: "Field engineers available in Lagos and major Nigerian cities for hardware and physical infrastructure." },
      { title: "Patch Management",           body: "Automated security patching and update management that keeps your fleet compliant and secure." },
      { title: "Asset Management",           body: "Full inventory of every device, licence, and piece of infrastructure in your environment." },
      { title: "SLA Reporting",              body: "Monthly reports on ticket volumes, response times, and uptime — full visibility, no surprises." },
    ],
    process: [
      { step: "01", title: "Onboarding",    body: "Document your environment, install monitoring agents, and brief our team on your setup." },
      { step: "02", title: "Stabilise",     body: "Resolve any outstanding issues, patch vulnerabilities, and baseline your infrastructure." },
      { step: "03", title: "Monitor",       body: "24/7 monitoring goes live with automated alerting and escalation protocols in place." },
      { step: "04", title: "Report",        body: "Monthly service reviews, proactive recommendations, and continuous improvement cycles." },
    ],
    stack: ["Microsoft Intune", "Azure AD", "ConnectWise", "N-able", "SolarWinds", "Jira Service Desk", "Zabbix", "PagerDuty"],
  },
  {
    slug:    "mobile-web-development",
    num:     "07",
    icon:    Smartphone,
    name:    "Mobile & Web Development",
    tagline: "Pixel-perfect on every screen.",
    desc:    "Cross-platform mobile apps and blazing-fast web experiences built for performance on every screen.",
    overview:"Your users are on their phones. We build cross-platform mobile apps and high-performance web experiences that feel native, load instantly, and keep people coming back.",
    color:   "#EC4899",
    glow:    "rgba(236,72,153,0.18)",
    tags:    ["React Native", "Flutter", "Swift", "Kotlin", "PWA", "Web Vitals"],
    features: [
      { title: "Cross-Platform Apps",       body: "React Native and Flutter apps that share one codebase but feel completely native on iOS and Android." },
      { title: "Native Development",        body: "Swift for iOS and Kotlin for Android when platform-specific performance is non-negotiable." },
      { title: "Progressive Web Apps",      body: "PWAs that work offline, install on any device, and load in under a second anywhere in the world." },
      { title: "App Store Optimisation",    body: "ASO strategy, screenshot design, and review management that drives organic downloads." },
      { title: "Performance Audits",        body: "Core Web Vitals optimisation, bundle analysis, and lighthouse scores above 95." },
      { title: "Push & Engagement",         body: "Push notifications, in-app messaging, and analytics that drive retention and revenue." },
    ],
    process: [
      { step: "01", title: "UX Research",   body: "User interviews, competitive analysis, and flow mapping before any design starts." },
      { step: "02", title: "Design",        body: "High-fidelity prototypes tested with real users before a single component is coded." },
      { step: "03", title: "Build",         body: "Component-driven development with automated testing and weekly releases to TestFlight/Play Beta." },
      { step: "04", title: "Launch",        body: "App Store/Play Store submission, launch plan, and post-launch monitoring." },
    ],
    stack: ["React Native", "Flutter", "Swift", "Kotlin", "Expo", "Firebase", "Next.js", "Tailwind CSS", "Fastlane"],
  },
  {
    slug:    "product-design",
    num:     "08",
    icon:    Palette,
    name:    "Product Design",
    tagline: "Design that users actually love.",
    desc:    "UX research, UI design, and design systems that users love. Pixel-perfect Figma handoffs and design tokens.",
    overview:"Great products are designed before they're built. We run the research, design the flows, and create the systems that turn complex requirements into interfaces people find intuitive, beautiful, and worth coming back to.",
    color:   "#FB923C",
    glow:    "rgba(251,146,60,0.18)",
    tags:    ["Figma", "UX Research", "Design System", "Prototyping", "Accessibility"],
    features: [
      { title: "UX Research",               body: "User interviews, usability testing, and analytics review that surface the real problems to solve." },
      { title: "Information Architecture",  body: "Site maps, user flows, and navigation systems that make complex products feel simple." },
      { title: "UI Design",                 body: "Pixel-perfect Figma designs with interactive prototypes before a single line of code is written." },
      { title: "Design Systems",            body: "Scalable component libraries and design tokens that keep every product touchpoint consistent." },
      { title: "Accessibility",             body: "WCAG 2.1 AA compliance baked in from the start — not bolted on at the end." },
      { title: "Design–Dev Handoff",        body: "Annotated specs, exported tokens, and collaborative reviews that eliminate build-to-design drift." },
    ],
    process: [
      { step: "01", title: "Discover",      body: "Stakeholder workshops, user research, and competitive benchmarking." },
      { step: "02", title: "Define",        body: "Problem framing, personas, and journey maps that align the whole team." },
      { step: "03", title: "Design",        body: "Wireframes → high-fidelity designs → interactive prototypes → usability testing." },
      { step: "04", title: "Deliver",       body: "Developer-ready specs, a live design system, and ongoing design support." },
    ],
    stack: ["Figma", "FigJam", "Maze", "Hotjar", "Storybook", "Zeroheight", "Lottie", "Framer"],
  },
  {
    slug:    "m365",
    num:     "09",
    icon:    LayoutGrid,
    name:    "M365 Provisioning",
    tagline: "Microsoft 365, done properly.",
    desc:    "Full Microsoft 365 licensing, migration, and management. Teams, SharePoint, Exchange, Intune, and Entra ID.",
    overview:"Microsoft 365 is only as good as the implementation behind it. We handle licensing, migration, configuration, and ongoing management so your team gets the productivity, security, and collaboration tools they actually need.",
    color:   "#0EA5E9",
    glow:    "rgba(14,165,233,0.18)",
    tags:    ["Microsoft 365", "Teams", "SharePoint", "Intune", "Entra ID", "Exchange"],
    features: [
      { title: "Tenant Setup & Migration",  body: "New tenant configuration or migration from Google Workspace/on-prem Exchange with zero data loss." },
      { title: "SharePoint & Teams",        body: "Information architecture, team structures, and governance policies your organisation will actually follow." },
      { title: "Intune Device Management",  body: "MDM and MAM policies that secure every device — corporate-owned and BYOD." },
      { title: "Entra ID & SSO",            body: "Identity management, conditional access policies, and SSO for your entire app portfolio." },
      { title: "Exchange & Email Security", body: "Anti-phishing, anti-spam, Defender for Office 365, and DKIM/DMARC configuration." },
      { title: "Licensing Optimisation",    body: "Right-size your licences, consolidate SKUs, and eliminate wasted spend." },
    ],
    process: [
      { step: "01", title: "Assess",        body: "Inventory current licences, identities, and collaboration patterns." },
      { step: "02", title: "Plan",          body: "Design the target tenant architecture, migration approach, and change management plan." },
      { step: "03", title: "Deploy",        body: "Phased rollout with testing, training sessions, and a helpdesk on standby." },
      { step: "04", title: "Manage",        body: "Ongoing licence management, security reviews, and user support." },
    ],
    stack: ["Microsoft 365", "Azure AD / Entra ID", "Microsoft Intune", "SharePoint Online", "Exchange Online", "Microsoft Teams", "Defender for M365"],
  },
  {
    slug:    "consultancy",
    num:     "10",
    icon:    Lightbulb,
    name:    "IT Consultancy",
    tagline: "Strategy first. Technology second.",
    desc:    "Strategic tech advisory and digital transformation roadmaps. CTO-as-a-Service, tech audits, vendor selection.",
    overview:"Technology decisions made without strategy cost years and millions to undo. Our consultancy practice gives you the senior technical leadership to make the right call — whether that's a tech audit, a transformation roadmap, or an embedded CTO.",
    color:   "#FBBF24",
    glow:    "rgba(251,191,36,0.18)",
    tags:    ["Strategy", "CTO-as-a-Service", "Digital Transformation", "Tech Audit", "Vendor Selection"],
    features: [
      { title: "CTO-as-a-Service",          body: "Fractional CTO embedded in your leadership team — strategic direction without the full-time cost." },
      { title: "Technology Audits",         body: "Comprehensive review of your stack, architecture, processes, and team — with a prioritised action plan." },
      { title: "Digital Transformation",    body: "End-to-end transformation programmes that modernise legacy systems without breaking the business." },
      { title: "Vendor Selection",          body: "Impartial RFP management and vendor evaluation so you buy the right technology for the right reasons." },
      { title: "Architecture Review",       body: "Expert review of your architecture decisions with actionable recommendations and risk assessments." },
      { title: "Team Building",             body: "Hiring frameworks, technical interview design, and engineering culture advisory." },
    ],
    process: [
      { step: "01", title: "Engage",        body: "Stakeholder interviews, document review, and immersion in your business context." },
      { step: "02", title: "Analyse",       body: "Technology, process, and people assessment against best-in-class benchmarks." },
      { step: "03", title: "Recommend",     body: "Prioritised roadmap with business cases, effort estimates, and risk-rated options." },
      { step: "04", title: "Implement",     body: "Optional hands-on delivery support to turn recommendations into results." },
    ],
    stack: ["TOGAF", "ITIL", "OKRs", "PRINCE2", "AWS Well-Architected", "DORA Metrics"],
  },
];

export default SERVICES;

export function getServiceBySlug(slug: string): ServiceData | undefined {
  return SERVICES.find(s => s.slug === slug);
}
